# Generated by Django 5.1.1 on 2024-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="No title", max_length=255),
        ),
    ]
