# Generated by Django 5.1.1 on 2024-10-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifytemplate',
            name='template',
        ),
        migrations.RemoveField(
            model_name='verifytemplate',
            name='user',
        ),
        migrations.AddField(
            model_name='template',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='VerifyTemplate',
        ),
    ]
