# Generated by Django 5.1.1 on 2024-10-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminApp", "0003_remove_verifytemplate_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="question",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
