# Generated by Django 5.1.1 on 2024-10-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mfa_method",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("sms", "SMS"), ("totp", "TOTP")],
                default="Email",
                max_length=20,
                null=True,
            ),
        ),
    ]
