# Generated by Django 5.1.1 on 2024-09-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
