# Generated by Django 5.1.1 on 2024-09-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mfa_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("authenticator", "Authenticator App"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
