# Generated by Django 5.1.1 on 2024-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_customuser_mfa_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="mfa_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mfa_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mfa_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("authenticator", "Authenticator App"),
                ],
                default="email",
                max_length=20,
                null=True,
            ),
        ),
    ]
