# Generated by Django 5.1.1 on 2024-10-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_mfa_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('LAWYER', 'Lawyer'), ('AUDITOR', 'Auditor')], default='USER', max_length=255),
        ),
    ]
