# Generated by Django 5.1.1 on 2024-10-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mfa_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("authenticator", "Authenticator"),
                ],
                default="authenticator",
                max_length=20,
                null=True,
            ),
        ),
    ]
