# Generated by Django 5.1.1 on 2024-10-08 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminApp", "0004_alter_template_category_alter_template_content_and_more"),
        ("lawyer", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerapproval",
            name="user_documents",
            field=models.ManyToManyField(blank=True, to="user.userdocument"),
        ),
        migrations.AddField(
            model_name="lawyerdocument",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminApp.template"
            ),
        ),
        migrations.AddField(
            model_name="lawyerapproval",
            name="lawyer_documents",
            field=models.ManyToManyField(blank=True, to="lawyer.lawyerdocument"),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminApp.template"
            ),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lawyerdocument",
            name="preferred_lawyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferred_lawyer_documents",
                to="lawyer.lawyerprofile",
            ),
        ),
        migrations.AddField(
            model_name="lawyerdocument",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lawyer.lawyerprofile"
            ),
        ),
        migrations.AddField(
            model_name="lawyerapproval",
            name="lawyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lawyer.lawyerprofile"
            ),
        ),
    ]
