# Generated by Django 5.1.1 on 2024-10-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_remove_verifytemplate_template_and_more'),
        ('lawyer', '0002_lawyerdocument_and_more'),
        ('user', '0003_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerapproval',
            name='user_documents',
            field=models.ManyToManyField(blank=True, to='user.userdocument'),
        ),
        migrations.AddField(
            model_name='lawyerdocument',
            name='preferred_lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_lawyer_documents', to='lawyer.lawyerprofile'),
        ),
        migrations.AddField(
            model_name='lawyerdocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.template'),
        ),
        migrations.AddField(
            model_name='lawyerdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer.lawyerprofile'),
        ),
        migrations.AddField(
            model_name='lawyerapproval',
            name='lawyer_documents',
            field=models.ManyToManyField(blank=True, to='lawyer.lawyerdocument'),
        ),
    ]
