# Generated by Django 5.1.1 on 2024-10-08 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminApp", "0004_alter_template_category_alter_template_content_and_more"),
        ("lawyer", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyerprofile",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminApp.template",
            ),
        ),
        migrations.AlterField(
            model_name="lawyerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lawyer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
