# Generated by Django 5.1.1 on 2024-10-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lawyer", "0003_lawyerapproval_user_documents_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lawyerprofile",
            old_name="preferred_language",
            new_name="prefered_language",
        ),
        migrations.RemoveField(
            model_name="lawyerprofile",
            name="mfa",
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="profile_pic",
            field=models.URLField(blank=True, null=True),
        ),
    ]
