# Generated by Django 5.1.1 on 2024-10-08 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "lawyer",
            "0004_rename_preferred_language_lawyerprofile_prefered_language_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lawyerprofile",
            name="template",
        ),
    ]
