# Generated by Django 5.1.1 on 2024-10-04 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminApp", "0003_remove_verifytemplate_template_and_more"),
        ("user", "0003_userprofile_email_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminApp.template",
            ),
        ),
    ]
