# Generated by Django 5.1.1 on 2024-10-08 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_userprofile_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdocument",
            old_name="prefered_lawyer",
            new_name="selected_lawyer",
        ),
    ]
